[build]
builder = "nixpacks"

[deploy]
startCommand = "python -m app.bot.telegram_bot"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.envs]
PYTHON_VERSION = "3.11.0" 